// topics.js — Word lists for the Imposter Game
// Each category contains at least 30 unique topics that players must describe

module.exports = {
  general: [
    'Pizza',
    'Airport',
    'Swimming pool',
    'Library',
    'Wedding',
    'Dentist',
    'Roller coaster',
    'Supermarket',
    'Football',
    'Museum',
    'Camping',
    'Karaoke',
    'Barbershop',
    'Traffic jam',
    'Elevator',
    'Laundromat',
    'Fire station',
    'Aquarium',
    'Casino',
    'Yoga class',
    'Road trip',
    'Haunted house',
    'Farmers market',
    'Movie theater',
    'Gym',
    'Post office',
    'Food truck',
    'Lighthouse',
    'Treehouse',
    'Escape room',
  ],

  family: [
    'Ice cream',
    'Playground',
    'Birthday cake',
    'Zoo',
    'Bedtime',
    'School bus',
    'Sandcastle',
    'Rainbow',
    'Teddy bear',
    'Tooth fairy',
    'Lemonade stand',
    'Pillow fort',
    'Pajama party',
    'Snowman',
    'Bubble bath',
    'Hide and seek',
    'Magic show',
    'Puppet show',
    'Treasure hunt',
    'Cartoon',
    'Water balloon',
    'Fairy tale',
    'Treehouse',
    'Animal crackers',
    'Night light',
    'Blanket fort',
    'Jump rope',
    'Snow day',
    'Finger painting',
    'Goldfish',
  ],

  adult: [
    'Hangover',
    'First date',
    'Job interview',
    'Online dating',
    'Skinny dipping',
    'Walk of shame',
    'Speed dating',
    'Tinder',
    'Blackout drunk',
    'Awkward silence',
    'Walk of fame',
    'Bachelor party',
    'Vegas trip',
    'Karaoke night',
    'Bar crawl',
    'Wine tasting',
    'Blind date',
    'Guilty pleasure',
    'One night stand',
    'Happy hour',
    'Brunch',
    'Office party',
    'Netflix and chill',
    'Morning after',
    'Beer pong',
    'Cocktail party',
    'Road trip',
    'Music festival',
    'House party',
    'After party',
  ],
};
